added adding of building functionality and linking of new rooms created with the building.
minerva-startup-spring2024/roommate-organizer pull request #18
Opened 2024-03-01 22:01 UTC by minerva-startup-spring2024

# Pull Request Template

## Added adding of building functionality and  linking of new rooms created with the building.

I added a adding building functionality such that if the user is the manager they can list a building and add the name and address of the building. A tenant can now choose a building and then proceed to create a new room such that the new room is linked with the building.

## 
[Link to Ticket] (https://www.notion.so/bathientran/Add-a-functionality-to-add-buildings-and-link-rooms-to-it-e460bdf1c8664897af73cc51c6e66dcb?pvs=4/).

Please indicate the ticket(s) in Notion that correspond to this PR.

- Ticket 1
- Ticket 2

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## What Has Changed

Please describe in bullets what you have changed.
-You can add  a new building
-If you create a room it is linked to the building.
-Changed the unique constraint in the prisma schema to allow linking of multiple rooms to one building. One to many

## How Has This Been Tested / How Can This Be Tested
-As admin:
-Navigate to  localhost/buildings as admin and enter a new building.
-Navigate to localhost/api/buildings to see the new entry
-For rooms create a new room and then navigate to 'npx prisma studio' to see the room addition and the linking of it with the building id.
-ignore the null entries in the room is building field. They were created before the linking was done and the field being nullable that was possible.

As tenant:
-Navigate to the buildings page and it should return the current buildings after which if you choose one it should redirect you to the rooms page where if create a new room it will now associate that room with the building of your choice.

Next:
Create the announcement model.

2024-03-04 23:52 UTC, bathientran requested changes
Good stuff! Just added a couple of small changes required

2024-03-04 23:52 UTC, bathientran commented on .env.local
Hm... this should really be removed, can you remove the delete? I'll add it to the .gitignore so that it won't be changed going forward

2024-03-04 23:52 UTC, bathientran commented on package-lock.json
> +        "react-router-dom": "^6.22.2",
We shouldn't need the `react-router-dom package`, Next.js provides routing as their main feature – let's remove that package

2024-03-04 23:52 UTC, bathientran commented on src/app/buildings/page.js
> +
No need for this anymore, we automatically check for login :)

2024-03-04 23:52 UTC, bathientran commented on src/app/buildings/page.js
> +
Same here actually

2024-03-13 01:19 UTC, closed without merging

2024-03-13 01:20 UTC, minerva-startup-spring2024 commented
Closed to avoid conflicts with main branch. Will push request once I've updated it to the current project status.