Login page Styling
minerva-startup-spring2024/roommate-organizer pull request #19
Opened 2024-03-04 20:13 UTC by Waiyego-Wangari

# Pull Request Template

## Updated the styling for the Login Page according to the Figma files 

Please include a summary of the change and which issue is fixed. Include the motivation and context, and list any dependencies that are required for this change.

## Link to Ticket

Please indicate the ticket(s) in Notion that correspond to this PR.
[Ticket](https://www.notion.so/bathientran/FRONTEND-Login-page-059b10b71eac4469a057ece665944690?pvs=4
)
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## What Has Changed

Please describe in bullets what you have changed.

- Added styling that matches the Figma design
- Imported reusable components from material UI

## How Has This Been Tested / How Can This Be Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- Go to X and do Y.

2024-03-04 23:57 UTC, bathientran requested changes
Looks really really good – just some minor comments about making it responsive

2024-03-04 23:57 UTC, bathientran commented on .env.local
Do you mind removing this delete from your commit? Realized I missed the file in the .gitignore and we need it to stay :D

2024-03-04 23:57 UTC, bathientran commented on src/app/login/page.css
Seems like this is focused on web – do we have any option for making it reactive for mobile?

2024-03-06 12:13 UTC, Waiyego-Wangari commented on src/app/login/page.css
Once I get this merged, I'll push up another PR for the responsiveness.

2024-03-06 12:23 UTC, Waiyego-Wangari commented on .env.local
Done! Thanks for catching that!

2024-03-06 16:47 UTC, vickipetrova approved these changes

2024-03-06 22:15 UTC, bathientran approved these changes

2024-03-07 09:38 UTC, merged