General 80 full chores
minerva-startup-spring2024/roommate-organizer pull request #24
Opened 2024-03-07 22:01 UTC by bathientran

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Include the motivation and context, and list any dependencies that are required for this change.

Adds the chores detail page.

## Link to Ticket

Please indicate the ticket(s) in Notion that correspond to this PR.

- https://www.notion.so/bathientran/Full-Chore-List-View-ed8e04b4a2454c15959bd4cf3ab1e0f5?pvs=4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## What Has Changed

Please describe in bullets what you have changed.

- Changes API routing to consolidate utils.
- Adds room members endpoint.
- Adds Image usage.
- Adds standardized color usage.
- Adds chore detail page with filtering for chores, updating chores, viewing chores, adding chores, selecting users to assign.

## How Has This Been Tested / How Can This Be Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

https://www.loom.com/share/6602ea79c7c84e938cfcad34bf42abb4?sid=7bd31719-f61d-4be7-b7ed-a965f1556e5a

2024-03-07 23:29 UTC, vickipetrova requested changes
I think this PR also includes the changes from the profile creation PR https://github.com/minerva-startup-spring2024/roommate-organizer/pull/23/ 

We should probably separate them?

2024-03-07 23:29 UTC, vickipetrova commented on assets/seed-images/user_image_1.jpg
aren't the assets added by the previous PR for the profile creation?

2024-03-07 23:31 UTC, bathientran commented on assets/seed-images/user_image_1.jpg
Oh I set the base incorrect, let me change that

2024-03-07 23:31 UTC, vickipetrova commented
<img width="916" alt="image" src="https://github.com/minerva-startup-spring2024/roommate-organizer/assets/90992029/3c561e67-dfbd-4f14-8ab0-bd22cd822822">

2024-03-07 23:32 UTC, bathientran commented
> <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/90992029/311068801-3c561e67-dfbd-4f14-8ab0-bd22cd822822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTQ2MDIsIm5iZiI6MTcwOTg1NDMwMiwicGF0aCI6Ii85MDk5MjAyOS8zMTEwNjg4MDEtM2M1NjFlNjctZGZiZC00ZjE0LThhYjAtYmQyMmNkODIyODIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIzMzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NGIyNWFmZmJjZjNlNThkZjQ0ZmM2MDdlNTgyNjZmNzdlNDRlYmZlY2M3M2FkMWU3YWMyMDQ2ZTk5NjI3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wKhUX9tknZTQ_5_V_YGI01mP26SjBB7oybJ1_ofJ7oc">

does npm install fix it? should just be an install

2024-03-09 11:06 UTC, vickipetrova commented
<img width="756" alt="image" src="https://github.com/minerva-startup-spring2024/roommate-organizer/assets/90992029/213e3b60-6a0a-4aec-a918-c5eee2241d88">
<img width="1054" alt="image" src="https://github.com/minerva-startup-spring2024/roommate-organizer/assets/90992029/fd8de504-e5d4-4006-ad89-a5632a84ea54">
https://github.com/advisories/GHSA-hhhv-q57g-882q

2024-03-09 11:31 UTC, vickipetrova approved these changes

2024-03-09 11:33 UTC, vickipetrova commented
> > <img alt="image" width="916" src="https://private-user-images.githubusercontent.com/90992029/311068801-3c561e67-dfbd-4f14-8ab0-bd22cd822822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTQ2MDIsIm5iZiI6MTcwOTg1NDMwMiwicGF0aCI6Ii85MDk5MjAyOS8zMTEwNjg4MDEtM2M1NjFlNjctZGZiZC00ZjE0LThhYjAtYmQyMmNkODIyODIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIzMzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NGIyNWFmZmJjZjNlNThkZjQ0ZmM2MDdlNTgyNjZmNzdlNDRlYmZlY2M3M2FkMWU3YWMyMDQ2ZTk5NjI3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wKhUX9tknZTQ_5_V_YGI01mP26SjBB7oybJ1_ofJ7oc">
> 
> does npm install fix it? should just be an install

i can't see the image, i tried again but i cant get past the login page (i sent the bug in telegram), idk if it happens just locally for me or if it's the same for other people -- https://t.me/c/2090124433/28/452

2024-03-09 20:12 UTC, merged