Adding rules
minerva-startup-spring2024/roommate-organizer pull request #45
Opened 2024-04-04 02:47 UTC by Chiamakabrowneyes

## Description

This feature adds a route for the the housing management to communicate rules for the tenants.

## Link to Ticket: 

Ticket: https://www.notion.so/bathientran/Rules-Page-181977aa180e4cdcbcfb04c5cf314117?pvs=4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## What Has Changed

Please describe in bullets what you have changed.

- Add rule section: and poplated the fields
- Added new route app/rules

## How Has This Been Tested / How Can This Be Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

Run the dev page and ensure that theres no bugs. Should be able to see the UI for the rules in "app/rules" route.

2024-04-04 10:58 UTC, vickipetrova commented
@Chiamakabrowneyes you should fix the deployment -- there's a check that fails, if we merge it rn it will break the deployment.

2024-04-04 18:34 UTC, vickipetrova commented
> @Chiamakabrowneyes you should fix the deployment -- there's a check that fails, if we merge it rn it will break the deployment.

Actually, the break wasn't from this PR. It was from a failed migration directly applied to the production database. I fixed that issue so now all checks go through. Let's leave this PR open for now. As we discussed in the retrospective today, the rules feature is not part of the MVP and we are prioritizing the MVP tasks for the next two weeks. If we have time and users request this type of feature we can extend it so that -- there's a way to see the rules, add them, edit them, delete them, etc.

2024-04-14 02:09 UTC, Chiamakabrowneyes commented
@vickipetrova @bathientran. 
Since we are done with the main MVP features. I've worked on the the backend functionailty for this rules component. 
![image](https://github.com/minerva-startup-spring2024/roommate-organizer/assets/89539046/fdf15f26-24f6-4bac-95ad-eae3917d2264)
![image](https://github.com/minerva-startup-spring2024/roommate-organizer/assets/89539046/adc6a683-fb00-4a47-a2a9-1708c99022a8)

2024-04-16 18:13 UTC, bathientran requested changes

2024-04-16 18:13 UTC, bathientran commented on src/app/_components/Login.js
Have you tried testing this change? We don't actually use this component anymore.

2024-04-16 18:22 UTC, Chiamakabrowneyes commented on src/app/_components/Login.js
Hey yeah, I tested it by running the app locally. It seems to work fine. 
I was reversing the changes that I had made, and that one seemed to pop up so I took it back to what I thought was its original version. 
The rules component doesn't directly use it though.

2024-04-16 18:27 UTC, bathientran commented on src/app/_components/Login.js
If it isn't part of the rules feature, do you mind removing it then? makes our PRs cleaner and doesn't add tech debt to our repo

2024-04-16 19:15 UTC, Chiamakabrowneyes commented on src/app/_components/Login.js
ALright on it

2024-04-16 19:22 UTC, Chiamakabrowneyes commented on src/app/_components/Login.js
Okay done, Can you add back the migrations. Cause I had deleted it locally (and I saw that you added in the initial commit)

2024-04-16 19:22 UTC, bathientran commented
Also you shouldn't be deleting the migrations, this would break our app, I fixed it in a previous commit. Could you add those back as well please? Thanks

2024-04-16 19:23 UTC, bathientran commented
Same for the local .env file don't delete that file

2024-04-16 19:45 UTC, Chiamakabrowneyes commented
I didnt delete the env file. Both of them are still present locally. idk why it shows as deleted. 

But yeah, I've added back the migrations. I had initially deleted it while trying to resolve the database error from earl;ier today

2024-04-16 19:50 UTC, bathientran approved these changes

2024-04-16 19:51 UTC, merged